### ISSUE TITLE
depending on GRAN packages

### ISSUE THREAD

**Issue by scworland** [USGS-R/smwrStats#10]
What is the preferred method for depending on USGS packages that are only available on GRAN/github, such as smwrStats? If a user just blindly tries to download a package with these dependencies:

```r
devtools::install_github("scworland-usgs/package_that_depends_on_smwrStats")
```
Then something like the following error will show up:

```r
ERROR: dependencies ‘smwrStats’ are not available for package ‘package_that_depends_on_smwrStats’
* removing ‘/Users/scworlan/Library/R/3.4/library/package_that_depends_on_smwrStats’
Installation failed: Command failed (1)
```
Of course this is not new information, and it seems that the suggested method to avoid this error is:

```r
rprofile_path = file.path(Sys.getenv("HOME"), ".Rprofile")
write('\noptions(repos=c(getOption(\'repos\'),
  CRAN=\'https://cloud.r-project.org\',
  USGS=\'https://owi.usgs.gov/R\'))\n',
    rprofile_path, 
    append =  TRUE)
```

Another option, which removes the need for requiring a user to change their Rprofile, is the just include a remote in the DESCRIPTION file:

```r
Remotes: 
    github::USGS-R/smwrQW
```
Is there a preferred method?

**Comment by ldecicco-USGS** [comment]
Arg...I wrote a comment, and accidentally closed the page without submitting.

The tricky thing with `smwrStats` is that there is some compiled code in there, so Windows users need to have the correct Rtools installed (since `install_github` will only install from "source"). 

I keep hoping that the field "Additional_repositories" in the DESCRIPTION file will start to fill that role, but as of the latest version of R, it's still just a line that doesn't actually do much, nothing on install.

So....my preferred style is to have your users get GRAN on their .Rprofile (as you mentioned above). I'd also recommend putting your package on GRAN, so they can install in the more standard `install.packages` function rather than `devtools::install_github`. If they are USGS, they don't need to worry then about the ever-maddening DOI security certification issue, and in general `install.packages` is much more robust.

That all being said, you could try the "Remotes" field above, it might work (I'd still be most worried about being able to install the compiled code). You could also fiddle with adding the packages `onLoad`, and making `smwrStats` a Suggested package...but I don't think this is easier for the user.

**Comment by scworland** [comment]
That makes sense. I didn't think about the possible Rtools issue. I will close this for now and we can reopen it if something else comes back up. My question was actually in reference to this pull request: wfarmer-usgs/PUBAD#14. The PUBAD package is used in a publication and  we are trying to make sure the model archive contains scripts that are easily reproducible on other people's machines.

**Comment by scworland** [comment]
Ok, so back to this. Someone tried to load the PUBAD package (even with the remotes in the DESCRIPTION file) and received the following error:

```r
Downloading GitHub repo wfarmer-usgs/PUBAD@master
from URL https://api.github.com/repos/wfarmer-usgs/PUBAD/zipball/master
Installing PUBAD
Downloading GitHub repo USGS-R/smwrQW@master
from URL https://api.github.com/repos/USGS-R/smwrQW/zipball/master
Error: running command '"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-
save --no-restore --quiet CMD config CC' had status 1
```

Which as you mention earlier, looks related to compiled C code. So I guess my "solution" in the pull request is indeed not a solution after all!
